# Generated by Django 5.1.4 on 2024-12-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50)),
                ('etag', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
                ('channel_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail_default_url', models.URLField()),
                ('thumbnail_default_width', models.IntegerField()),
                ('thumbnail_default_height', models.IntegerField()),
                ('thumbnail_medium_url', models.URLField()),
                ('thumbnail_medium_width', models.IntegerField()),
                ('thumbnail_medium_height', models.IntegerField()),
                ('thumbnail_high_url', models.URLField()),
                ('thumbnail_high_width', models.IntegerField()),
                ('thumbnail_high_height', models.IntegerField()),
                ('channel_title', models.CharField(max_length=255)),
                ('live_broadcast_content', models.CharField(max_length=50)),
                ('publish_time', models.DateTimeField()),
            ],
        ),
    ]
