# Generated by Django 5.1.4 on 2024-12-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoSearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='query',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
